language: node_js

node_js:
   - "9"

sudo: required

services:
  - docker

cache:
  directories:
    - ./node_modules

branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker build -t mensaitalia/budget-front:1.0.$TRAVIS_BUILD_NUMBER . && docker push mensaitalia/budget-front:1.0.$TRAVIS_BUILD_NUMBER


notifications:
  slack:
    rooms:
      - ingmmo:SW0ahzRuwFIJKKAlQPzGRg0f#prj-mensa
      - ingmmo:SW0ahzRuwFIJKKAlQPzGRg0f#travisbuilds
